# Generated by Django 3.2.5 on 2021-07-26 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('spesification', models.CharField(choices=[('WEB DEVELOPMENT', 'WEB DEVELOPMENT'), ('MOBILE APP DEVELOPMENT', 'MOBILE APP DEVELOPMENT'), ('DESKTOP DEVELOPMENT', 'DESKTOP DEVELOPMENT')], default='WEB DEVELOPMENT', max_length=23)),
                ('developer_tech', models.CharField(choices=[('FRONTEND', 'FRONTEND'), ('BACKEND', 'BACKEND'), ('WEB FULLSTACK', 'WEB FULLSTACK'), ('ANDROID', 'ANDROID'), ('IOS', 'IOS'), ('FLUTTER', 'FLUTTER'), ('REACT NATIVE', 'REACT NATIVE'), ('DESKTOP APPS', 'DESKTOP APPS')], default='FRONTEND', max_length=14)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('spesification', models.CharField(choices=[('WEB DEVELOPMENT', 'WEB DEVELOPMENT'), ('MOBILE APP DEVELOPMENT', 'MOBILE APP DEVELOPMENT'), ('DESKTOP DEVELOPMENT', 'DESKTOP DEVELOPMENT')], default='WEB DEVELOPMENT', max_length=23)),
                ('developer_tech', models.CharField(choices=[('FRONTEND', 'FRONTEND'), ('BACKEND', 'BACKEND'), ('WEB FULLSTACK', 'WEB FULLSTACK'), ('ANDROID', 'ANDROID'), ('IOS', 'IOS'), ('FLUTTER', 'FLUTTER'), ('REACT NATIVE', 'REACT NATIVE'), ('DESKTOP APPS', 'DESKTOP APPS')], default='FRONTEND', max_length=14)),
                ('level', models.CharField(choices=[('JUNIOR', 'JUNIOR'), ('MIDDLE', 'MIDDLE'), ('SENIOR', 'SENIOR')], default='JUNIOR', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('payment_status', models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], default='UNPAID', max_length=7)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='M', max_length=7, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.group')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Subjects_Img')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=150)),
                ('students', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('lesson_time', models.CharField(choices=[('10:00 - 12:00', '10:00 - 12:00'), ('14:00 - 16:00', '14:00 - 16:00'), ('17:00 - 19:00', '17:00 - 19:00')], default='10:00 - 12:00', max_length=15)),
                ('lesson_status', models.CharField(choices=[('PLANNED', 'PLANNED'), ('COMPLETED', 'COMPLETED'), ('CANCELED', 'CANCELED')], default='PLANNED', max_length=10)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.group')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.mentor')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.mentor'),
        ),
    ]
