# Generated by Django 3.2.5 on 2021-07-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='students',
        ),
        migrations.AddField(
            model_name='subjects',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.Student'),
        ),
    ]
